name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: free up disk space by removing /opt/hostedtoolcache
      run: rm -rf /opt/hostedtoolcache
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.CONTAINERHUB_USERNAME }}
        password: ${{ secrets.CONTAINERHUB_TOKEN }}
    -
      name: build
      run: make build
    - 
      name: push
      run: make publish
    - 
      name: Extract Branch Name
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - 
      name: Extract Tag Name
      run: echo "TAG=$(git describe --exact-match --tags HEAD)" >> $GITHUB_ENV
    - 
      name: get VERSION from config.env
      run:  grep "^VERSION" config.env >> $GITHUB_ENV
    -
      name: push version
      if: env.BRANCH == 'main' && env.TAG == env.VERSION
      run: make publish-version
